version: '3.1'
services:
  moebius:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    image: moebius
    container_name: moebius
